# Generated by Django 3.0.8 on 2020-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcheck',
            name='check_number',
            field=models.CharField(max_length=10),
        ),
    ]
