# Generated by Django 3.0.8 on 2020-07-23 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_allegry_disease_health_surgery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allegry',
            old_name='allgergy_name',
            new_name='allergy_name',
        ),
        migrations.AlterField(
            model_name='allegry',
            name='health',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='account.Health'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='health',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='account.Health'),
        ),
        migrations.AlterField(
            model_name='health',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='health',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='account.Health'),
        ),
    ]
