# Generated by Django 3.0.8 on 2020-07-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200723_0553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allegry',
            new_name='Allergy',
        ),
    ]
