# Generated by Django 3.0.8 on 2020-07-23 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200723_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healths', to=settings.AUTH_USER_MODEL),
        ),
    ]
