# Generated by Django 3.0.8 on 2020-08-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_remove_newsletter_url'),
        ('account', '0010_auto_20200723_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_tags',
            field=models.ManyToManyField(to='newsletters.Tag'),
        ),
    ]
