# Generated by Django 3.0.8 on 2020-08-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_remove_newsletter_url'),
        ('account', '0011_user_like_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribes',
            field=models.ManyToManyField(to='newsletters.NewsLetter'),
        ),
    ]
