# Generated by Django 3.0.8 on 2020-08-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(to='newsletters.Tag'),
        ),
    ]
